export const FETCH_USERS = "FETCH_USERS";
export const SUCCESS_FETCH_USERS = "SUCCESS_FETCH_USERS";
export const ERROR_FETCH_USERS = "ERROR_FETCH_USERS";

export const SAVE_USER_ALBUMS = "SAVE_USER_ALBUMS";
export const SAVE_USER_POSTS = "SAVE_USER_POSTS";

export const FETCH_USER_POSTS = "FETCH_USER_POSTS";
export const SUCCESS_GET_USER_POSTS = "SUCCESS_GET_USER_POSTS";
export const ERROR_USER_POSTS = "ERROR_USER_POSTS"; 